/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ClientSessionRouteImport } from './routes/client-session'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DynamicPageListComponentRouteImport } from './routes/_dynamicPage/$listComponent'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthTwoFaRouteImport } from './routes/_auth/two-fa'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthNotVerifiedEmailRouteImport } from './routes/_auth/not-verified-email'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgetPasswordRouteImport } from './routes/_auth/forget-password'
import { Route as AuthUserProfileRouteImport } from './routes/_auth/User-Profile'
import { Route as AuthRegisterRouteImport } from './routes/_auth/Register'
import { Route as DynamicPageAssociationNameRouteImport } from './routes/_dynamicPage/association/$name'
import { Route as DynamicPageObjectNameObject_idIdIndexRouteImport } from './routes/_dynamicPage/$objectName/$object_id/$id/index'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientSessionRoute = ClientSessionRouteImport.update({
  id: '/client-session',
  path: '/client-session',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DynamicPageListComponentRoute =
  DynamicPageListComponentRouteImport.update({
    id: '/_dynamicPage/$listComponent',
    path: '/$listComponent',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/_auth/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTwoFaRoute = AuthTwoFaRouteImport.update({
  id: '/_auth/two-fa',
  path: '/two-fa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/_auth/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNotVerifiedEmailRoute = AuthNotVerifiedEmailRouteImport.update({
  id: '/_auth/not-verified-email',
  path: '/not-verified-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgetPasswordRoute = AuthForgetPasswordRouteImport.update({
  id: '/_auth/forget-password',
  path: '/forget-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUserProfileRoute = AuthUserProfileRouteImport.update({
  id: '/_auth/User-Profile',
  path: '/User-Profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/Register',
  path: '/Register',
  getParentRoute: () => rootRouteImport,
} as any)
const DynamicPageAssociationNameRoute =
  DynamicPageAssociationNameRouteImport.update({
    id: '/_dynamicPage/association/$name',
    path: '/association/$name',
    getParentRoute: () => rootRouteImport,
  } as any)
const DynamicPageObjectNameObject_idIdIndexRoute =
  DynamicPageObjectNameObject_idIdIndexRouteImport.update({
    id: '/_dynamicPage/$objectName/$object_id/$id/',
    path: '/$objectName/$object_id/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client-session': typeof ClientSessionRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/Register': typeof AuthRegisterRoute
  '/User-Profile': typeof AuthUserProfileRoute
  '/forget-password': typeof AuthForgetPasswordRoute
  '/login': typeof AuthLoginRoute
  '/not-verified-email': typeof AuthNotVerifiedEmailRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/two-fa': typeof AuthTwoFaRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/$listComponent': typeof DynamicPageListComponentRoute
  '/association/$name': typeof DynamicPageAssociationNameRoute
  '/$objectName/$object_id/$id': typeof DynamicPageObjectNameObject_idIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client-session': typeof ClientSessionRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/Register': typeof AuthRegisterRoute
  '/User-Profile': typeof AuthUserProfileRoute
  '/forget-password': typeof AuthForgetPasswordRoute
  '/login': typeof AuthLoginRoute
  '/not-verified-email': typeof AuthNotVerifiedEmailRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/two-fa': typeof AuthTwoFaRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/$listComponent': typeof DynamicPageListComponentRoute
  '/association/$name': typeof DynamicPageAssociationNameRoute
  '/$objectName/$object_id/$id': typeof DynamicPageObjectNameObject_idIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client-session': typeof ClientSessionRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_auth/Register': typeof AuthRegisterRoute
  '/_auth/User-Profile': typeof AuthUserProfileRoute
  '/_auth/forget-password': typeof AuthForgetPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/not-verified-email': typeof AuthNotVerifiedEmailRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/two-fa': typeof AuthTwoFaRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_dynamicPage/$listComponent': typeof DynamicPageListComponentRoute
  '/_dynamicPage/association/$name': typeof DynamicPageAssociationNameRoute
  '/_dynamicPage/$objectName/$object_id/$id/': typeof DynamicPageObjectNameObject_idIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client-session'
    | '/unauthorized'
    | '/Register'
    | '/User-Profile'
    | '/forget-password'
    | '/login'
    | '/not-verified-email'
    | '/reset-password'
    | '/two-fa'
    | '/verify-email'
    | '/$listComponent'
    | '/association/$name'
    | '/$objectName/$object_id/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client-session'
    | '/unauthorized'
    | '/Register'
    | '/User-Profile'
    | '/forget-password'
    | '/login'
    | '/not-verified-email'
    | '/reset-password'
    | '/two-fa'
    | '/verify-email'
    | '/$listComponent'
    | '/association/$name'
    | '/$objectName/$object_id/$id'
  id:
    | '__root__'
    | '/'
    | '/client-session'
    | '/unauthorized'
    | '/_auth/Register'
    | '/_auth/User-Profile'
    | '/_auth/forget-password'
    | '/_auth/login'
    | '/_auth/not-verified-email'
    | '/_auth/reset-password'
    | '/_auth/two-fa'
    | '/_auth/verify-email'
    | '/_dynamicPage/$listComponent'
    | '/_dynamicPage/association/$name'
    | '/_dynamicPage/$objectName/$object_id/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientSessionRoute: typeof ClientSessionRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthUserProfileRoute: typeof AuthUserProfileRoute
  AuthForgetPasswordRoute: typeof AuthForgetPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthNotVerifiedEmailRoute: typeof AuthNotVerifiedEmailRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthTwoFaRoute: typeof AuthTwoFaRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  DynamicPageListComponentRoute: typeof DynamicPageListComponentRoute
  DynamicPageAssociationNameRoute: typeof DynamicPageAssociationNameRoute
  DynamicPageObjectNameObject_idIdIndexRoute: typeof DynamicPageObjectNameObject_idIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-session': {
      id: '/client-session'
      path: '/client-session'
      fullPath: '/client-session'
      preLoaderRoute: typeof ClientSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dynamicPage/$listComponent': {
      id: '/_dynamicPage/$listComponent'
      path: '/$listComponent'
      fullPath: '/$listComponent'
      preLoaderRoute: typeof DynamicPageListComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/two-fa': {
      id: '/_auth/two-fa'
      path: '/two-fa'
      fullPath: '/two-fa'
      preLoaderRoute: typeof AuthTwoFaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/not-verified-email': {
      id: '/_auth/not-verified-email'
      path: '/not-verified-email'
      fullPath: '/not-verified-email'
      preLoaderRoute: typeof AuthNotVerifiedEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forget-password': {
      id: '/_auth/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof AuthForgetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/User-Profile': {
      id: '/_auth/User-Profile'
      path: '/User-Profile'
      fullPath: '/User-Profile'
      preLoaderRoute: typeof AuthUserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/Register': {
      id: '/_auth/Register'
      path: '/Register'
      fullPath: '/Register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dynamicPage/association/$name': {
      id: '/_dynamicPage/association/$name'
      path: '/association/$name'
      fullPath: '/association/$name'
      preLoaderRoute: typeof DynamicPageAssociationNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dynamicPage/$objectName/$object_id/$id/': {
      id: '/_dynamicPage/$objectName/$object_id/$id/'
      path: '/$objectName/$object_id/$id'
      fullPath: '/$objectName/$object_id/$id'
      preLoaderRoute: typeof DynamicPageObjectNameObject_idIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientSessionRoute: ClientSessionRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthUserProfileRoute: AuthUserProfileRoute,
  AuthForgetPasswordRoute: AuthForgetPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthNotVerifiedEmailRoute: AuthNotVerifiedEmailRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthTwoFaRoute: AuthTwoFaRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  DynamicPageListComponentRoute: DynamicPageListComponentRoute,
  DynamicPageAssociationNameRoute: DynamicPageAssociationNameRoute,
  DynamicPageObjectNameObject_idIdIndexRoute:
    DynamicPageObjectNameObject_idIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
